name: Daily next-day summary (22:00 local)

on:
  # 20:00 UTC ≈ 22:00 CEST (léto), 21:00 UTC ≈ 22:00 CET (zima)
  schedule:
    - cron: '0 20 * * *'   # léto
    - cron: '0 21 * * *'   # zima
  workflow_dispatch:
    inputs:
      pairs:
        description: 'FX páry (bez lomítka, čárkou oddělené)'
        required: false
        default: 'EURUSD,USDJPY'

jobs:
  run-summary:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: daily-summary
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      - name: Run daily summary (nextday_summary.py)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TZ: Europe/Prague
          PAIRS: ${{ inputs.pairs || 'EURUSD,USDJPY' }}
        run: |
          echo "Cílové páry: $PAIRS"
          python scripts/nextday_summary.py --pairs "$PAIRS"
