name: Daily next-day summary (22:00 CET)

on:
  schedule:
    - cron: "0 20 * * *"   # 22:00 CET (20:00 UTC) – uprav si dle potřeby
  workflow_dispatch:
    inputs:
      pairs:
        description: "Seznam párů oddělený čárkou"
        required: false
        default: "EURUSD,USDJPY"

jobs:
  run-summary:
    runs-on: ubuntu-latest
    env:
      PAIRS: ${{ inputs.pairs != '' && inputs.pairs || 'EURUSD,USDJPY' }}
      TZ: Europe/Prague
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TG_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}   # pro notify.py
      TG_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}       # pro notify.py

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (optional)
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      - name: Skip on weekend
        run: |
          dow=$(date +%u)
          if [ "$dow" -ge 6 ]; then
            echo "Víkend – workflow se přeskočí."
            python scripts/notify.py "ℹ️ Daily summary přeskočeno (víkend). Páry: <code>$PAIRS</code>"
            exit 0
          fi

      - name: Notify Telegram
        if: always()
        shell: bash
        run: |
          code="${{ steps.runpy.outputs.exit_code }}"
          # default message (error)
          msg="❌ Daily summary selhalo (exit $code). Páry: <code>$PAIRS</code>"
          # přepiš podle exit kódu
          if [ "$code" = "2" ]; then msg="✅ Daily summary proběhlo: <b>bez nových dat</b>. Páry: <code>$PAIRS</code>"; fi
          if [ "$code" = "0" ]; then msg="✅ Daily summary <b>hotovo</b>. Páry: <code>$PAIRS</code>"; fi
          echo "Sending Telegram message: $msg"
          python scripts/notify.py "$msg" || echo "Notify failed (workflow stále OK)"


      

