name: Daily next-day summary (22:00 CET)

on:
  # Spouštět KAŽDÝ den (i o víkendu)
  # 20:00 UTC ≈ 22:00 CET/CEST
  schedule:
    - cron: '0 20 * * *'
  # Ručně spustitelné s volitelným vstupem páru
  workflow_dispatch:
    inputs:
      pairs:
        description: 'FX páry (bez lomítka, čárkou oddělené)'
        required: false
        default: 'EURUSD,USDJPY'

jobs:
  run-summary:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    concurrency:
      group: daily-summary
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # ŽÁDNÝ "Skip on weekend" – poběží i v sobotu/neděli
      - name: Run daily summary (fundament)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TZ: Europe/Prague
          PAIRS: ${{ inputs.pairs || 'EURUSD,USDJPY' }}
        run: |
          echo "Cílové páry: $PAIRS"
          python scripts/fundament_summary.py --pairs "$PAIRS"
