name: Test Telegram
on: workflow_dispatch
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
               -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
               -d text="✅ Test: GitHub Actions posílá zprávy do Telegramu"
